### ISSUE TITLE
'index.ts is missing from the typescript compilation' error

### ISSUE THREAD

**Issue by blubberbo** [zurfyx/angular-contents#8]
hi,

I am getting the following error: `node_modules/angular-contents/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).`

this is my `package.json`:

```
"dependencies": {
    "@angular/animations": "~7.2.12",
    "@angular/common": "~7.2.12",
    "@angular/compiler": "~7.2.12",
    "@angular/core": "~7.2.12",
    "@angular/forms": "~7.2.12",
    "@angular/platform-browser": "~7.2.12",
    "@angular/platform-browser-dynamic": "~7.2.12",
    "@angular/router": "~7.2.12",
    "angular-contents": "^7.0.0",
    "core-js": "^2.6.5",
    "ngx-page-scroll": "^6.0.0-beta.1",
    "ngx-page-scroll-core": "^6.0.0-beta.1",
    "rxjs": "^6.4.0",
    "tslib": "^1.9.3",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler-cli": "^7.2.12",
    "@angular/language-service": "~7.2.12",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~11.13.0",
    "codelyzer": "~5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.2",
    "rxjs-compat": "^6.4.0",
    "ts-node": "~8.0.3",
    "tslint": "~5.15.0",
    "typescript": "^3.2.4"
  }
```

**Comment by javier505mx** [comment]
Same problem here.

`"dependencies": {
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@azure/msal-angular": "^0.1.2",
    "angular-contents": "^7.0.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "oidc-client": "^1.8.2",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.5.2",
    "tslib": "^1.9.0",
    "xlsx": "^0.14.3",
    "zone.js": "~0.8.26"
  },`

**Comment by nfgallimore** [comment]
Same error here.

`ERROR in ./node_modules/angular-contents/src/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: apppathurl\node_modules\angular-contents\src\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and
ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (apppathurlp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (apppathurl\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`
